### ISSUE TITLE
product/on-sale 요청 보낼 때 격회로 응답 오류나는 현상 수정

### ISSUE THREAD

**Issue by popopy0412** [SWM-WeLike2Coding/ELSwhere-product-service#28]
해당 요청 보낼 때 격회로 오류, 정상, 오류, 정상 응답이 반복되네용.. 확인하고 수정 부탁드립니다!

**Comment by kjungw1025** [comment]
해결완료했습니다!

도커 컨테이너로 현재 실행중인 것과 닫혀있는 product-service 두개가 eureka 서버에 등록되어있어서
위와 같은 오류가 발생했었습니다 ㅠㅠ
