### ISSUE TITLE
특정 상품 세부 정보 조회 API 미작동 오류

### ISSUE THREAD

**Issue by popopy0412** [SWM-WeLike2Coding/ELSwhere-product-service#33]
특정 상품에 대해 세부 정보를 조회하는 API 호출 시 조회가 되지 않는 오류가 발생했습니다

**Comment by kjungw1025** [comment]
백엔드에는 이상이 없는 것으로 파악되었습니다

https://github.com/SWM-WeLike2Coding/ELSwhere-mobile/issues/59
