### ISSUE TITLE
일부 종목 Ticker 조회 및 검색 불가

### ISSUE THREAD

**Issue by popopy0412** [SWM-WeLike2Coding/ELSwhere-product-service#73]
"Eli Lilly and Company" 종목이 현재 상세 검색과, 상품 단건 조회시 응답에 Ticker가 포함되지 않고 있습니다! 수정 부탁드립니다!

**Comment by kjungw1025** [comment]
slack을 통해서 알림 받은 새로운 티커 정보를 수동으로 db에 적재하면서 놓친 부분이 있었네요 ㅎㅎ
추가적으로 수정하면서 발견한건데, 파싱할 때 받아오는 엑셀 파일에 기초자산명 자체가 누락된 상품이 존재해서
그 부분도 수정해놨습니다!
